### ISSUE TITLE
Which version of sceptre is this?

### ISSUE THREAD

**Issue by s50600822** [cloudreach/sceptre-wordpress-example#1]
➜  sceptre-wordpress-example git:(master) sceptre --version
Sceptre, version 2.1.5
➜  sceptre-wordpress-example git:(master) sceptre launch-env prod
Usage: sceptre [OPTIONS] COMMAND [ARGS]...
Try "sceptre --help" for help.

Error: No such command "launch-env".

**Comment by giuliocalzo** [comment]
this repo use sceptre 1.4.2 not the  new version
