### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tabularjon** [cloudreach/sceptre-wordpress-example#2]
I am a newby to Sceptre and tried out the very basic VPC setup, which worked. Then I found this, which seemed to take it to the next level — I thought once I got this working this would be fantastic I can just customise it to my requirements. However, I am obviously missing something. The readme seems out of date or inaccurate, so I wondered if someone can help.

```
sceptre launch-env dev
Usage: sceptre [OPTIONS] COMMAND [ARGS]...
Try 'sceptre --help' for help.

Error: No such command 'launch-env'.
```

So I tried guessing:

```
sceptre launch dev
"prod/security-groups: Dependency vpc not found. Valid dependency names are: prod/vpc.yaml, prod/security-groups.yaml, prod/efs.yaml, dev/efs.yaml, dev/rds.yaml, dev/security-groups.yaml, prod/wordpress.yaml, prod/rds.yaml, dev/wordpress.yaml, dev/role.yaml, dev/vpc.yaml. Please make sure that your dependencies stack_outputs have their full path from `config` defined."
```

Not sure why, but it doesn’t seem to recognise the .py templates, even though I have troposphere installed and it appears to be called correctly although I am no expert. 

Is it just the readme is not up-to-date, or have I missed something?

**Comment by tabularjon** [comment]
It seems this was intended for an old version of Sceptre. It would be good if the readme could be updated to reflect this. Are there any plans to updated this to work Sceptre v2? Or, is there any guidance on what would be required to update it?

**Comment by nunogrl** [comment]
Just submitted a pull request with the changes for version 2.
This requires pre-existing role on your account to execute the commands or a default aws account defined.
Also most likely you must create a new bucket, as buckets have unique names.
So to have this working on your machine update the `config/dev/config.yaml` and `config/prod/config.yaml`
for instance for dev and prod config file, fill the variables as in your `~/.aws/credentials` file

```
---
project_code: wordpress
profile: awsprofile-dev
region: eu-west-1
template_bucket_name: sceptre-artifacts-wordpress-XXXXXXXXX

```


```
---
project_code: wordpress
profile: awsprofile-prod
region: eu-west-1
template_bucket_name: sceptre-artifacts-wordpress-XXXXXXXXX

```

**project_code**: will be part of the stack name

**profile and region**: variables will call directly you aws-cli configuration. update accordingly.

**template_bucket_name**: this is optional, but a good practice. If not defined the templates will be called using boto3 and there's a size limit for the template size. update accordingly.

**Comment by giuliocalzo** [comment]
thanks to @nunogrl sceptre V2 is now working #3
